'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { StatusBadge } from './status-badge';
import { formatMoney } from '@/lib/travel/money';
import type { Booking } from '@/types/travel';

export function BookingDetailPage({ bookingId }: { bookingId: string }) {
  const [booking, setBooking] = useState<Booking | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(() => fetch(`/api/travel/bookings/${bookingId}`).then(async (r) => { const b = await r.json() as { booking?: Booking; error?: string }; if (!r.ok || !b.booking) throw new Error(b.error ?? 'Could not load booking'); setBooking(b.booking); }).catch((e: Error) => setError(e.message)), [bookingId]);
  useEffect(() => { void load(); }, [load]);
  async function payment(e: FormEvent<HTMLFormElement>, kind: 'customer' | 'supplier') { e.preventDefault(); const form = e.currentTarget; const data = new FormData(form); setBusy(true); const r = await fetch(`/api/travel/bookings/${bookingId}/${kind}-payments`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(Object.fromEntries(data.entries())) }); setBusy(false); if (r.ok) { form.reset(); await load(); } else { const b = await r.json() as { error?: string }; setError(b.error ?? 'Could not record payment'); } }
  if (!booking) return <div className="py-24 text-center text-muted-foreground">{error ?? 'Loading booking…'}</div>;
  return <div className="space-y-5"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-bold">{booking.booking_number}</h1><p className="text-muted-foreground">{booking.traveller_name ?? 'Traveller'} · {booking.destination_primary ?? 'Destination TBC'}</p></div><StatusBadge value={booking.status} /></div>{error ? <p className="text-sm text-destructive">{error}</p> : null}<div className="grid gap-4 lg:grid-cols-3"><FinancialCard title="Customer" rows={[['Package price',booking.selling_price_before_tax],['GST',booking.gst_amount],['Traveller total',booking.traveller_total],['Received',booking.amount_received],['Balance',booking.customer_balance]]} /><FinancialCard title="Supplier" rows={[['Supplier cost',booking.supplier_cost],['Paid',booking.supplier_amount_paid],['Balance',booking.supplier_balance]]} /><FinancialCard title="Oliday" rows={[['Selling price excl tax',booking.selling_price_before_tax],['Supplier cost',booking.supplier_cost],['Gross profit',booking.gross_profit],['Margin',`${booking.margin_pct}%`]]} /></div><div className="grid gap-4 lg:grid-cols-2"><PaymentForm title="Record customer payment" kind="customer" busy={busy} onSubmit={payment} /><PaymentForm title="Record supplier payment" kind="supplier" busy={busy} onSubmit={payment} /></div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Customer payment history</CardTitle></CardHeader><CardContent className="space-y-2">{booking.customer_payments?.map((p) => <div className="flex justify-between border-b py-2" key={p.id}><span>{p.payment_date} · {p.payment_method}</span><span>{formatMoney(p.amount)} · {p.payment_status}</span></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Supplier payment history</CardTitle></CardHeader><CardContent className="space-y-2">{booking.supplier_payments?.map((p) => <div className="flex justify-between border-b py-2" key={p.id}><span>{p.due_date ?? p.paid_at?.slice(0,10) ?? '—'} · {p.payment_method}</span><span>{formatMoney(p.amount)} · {p.status}</span></div>)}</CardContent></Card></div></div>;
}
function FinancialCard({ title, rows }: { title: string; rows: [string,string][] }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-2">{rows.map(([label,value], i) => <div className={`flex justify-between ${i === rows.length - 1 ? 'border-t pt-2 font-bold' : ''}`} key={label}><span className="text-muted-foreground">{label}</span><span>{value.endsWith('%') ? value : formatMoney(value)}</span></div>)}</CardContent></Card>; }
function PaymentForm({ title, kind, busy, onSubmit }: { title: string; kind: 'customer' | 'supplier'; busy: boolean; onSubmit: (e: FormEvent<HTMLFormElement>, kind: 'customer' | 'supplier') => void }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-2" onSubmit={(e) => onSubmit(e,kind)}><div><Label htmlFor={`${kind}-amount`}>Amount</Label><Input id={`${kind}-amount`} name="amount" type="number" min="0.01" step="0.01" required /></div><div><Label htmlFor={`${kind}-method`}>Method</Label><select id={`${kind}-method`} name="payment_method" className="h-8 w-full rounded-lg border bg-background px-2"><option>UPI</option><option>BANK_TRANSFER</option><option>PAYMENT_GATEWAY</option><option>CARD</option><option>CASH</option><option>OTHER</option></select></div><div><Label htmlFor={`${kind}-ref`}>Reference</Label><Input id={`${kind}-ref`} name="transaction_reference" /></div><div><Label htmlFor={`${kind}-date`}>{kind === 'customer' ? 'Payment date' : 'Due date'}</Label><Input id={`${kind}-date`} name={kind === 'customer' ? 'payment_date' : 'due_date'} type="date" /></div>{kind === 'supplier' ? <input type="hidden" name="status" value="PAID" /> : <input type="hidden" name="payment_status" value="RECEIVED" />}<Button disabled={busy} className="sm:col-span-2">Record payment</Button></form></CardContent></Card>; }
