'use client';

import Image from 'next/image';
import { useMemo, useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import type { Itinerary, TravelLead } from '@/types/travel';

type DayDraft = { day_number: number; date: string; title: string; description: string; hotel: string; meals: string; transport: string; activities: string };
type Draft = { itinerary_id: string | null; status: string; title: string; summary: string; hero_image_url: string; inclusions: string; exclusions: string; notes: string; days: DayDraft[] };

export function ItineraryBuilder({ lead, itineraries, onSaved }: { lead: TravelLead; itineraries: Itinerary[]; onSaved: () => void }) {
  const latest = itineraries[0] ?? null;
  const [draft, setDraft] = useState<Draft>(() => latest ? fromItinerary(latest) : freshDraft(lead));
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const saved = useMemo(() => itineraries.find((i) => i.id === draft.itinerary_id) ?? null, [itineraries, draft.itinerary_id]);

  const updateDay = (index: number, patch: Partial<DayDraft>) => setDraft((d) => ({ ...d, days: d.days.map((day, i) => i === index ? { ...day, ...patch } : day) }));
  const renumber = (days: DayDraft[]) => days.map((day, i) => ({ ...day, day_number: i + 1 }));
  const move = (index: number, by: number) => setDraft((d) => { const days = [...d.days]; const target = index + by; if (target < 0 || target >= days.length) return d; [days[index], days[target]] = [days[target], days[index]]; return { ...d, days: renumber(days) }; });

  async function save(): Promise<Itinerary | null> {
    setBusy(true); setMessage(null);
    const response = await fetch(`/api/travel/leads/${lead.id}/itineraries`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...draft, itinerary_id: saved?.status === 'DRAFT' ? draft.itinerary_id : null, days: draft.days.map((day) => ({ ...day, activities: day.activities.split(/\r?\n|,/).map((v) => v.trim()).filter(Boolean) })) }) });
    const body = await response.json() as { itinerary?: Itinerary; error?: string };
    setBusy(false);
    if (!response.ok || !body.itinerary) { setMessage(body.error ?? 'Could not save itinerary'); return null; }
    setDraft(fromItinerary(body.itinerary)); setMessage('Draft saved'); onSaved(); return body.itinerary;
  }

  async function finalize() { const itinerary = await save(); if (!itinerary) return; setBusy(true); const r = await fetch(`/api/travel/itineraries/${itinerary.id}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status: 'FINAL' }) }); const body = await r.json() as { itinerary?: Itinerary }; setBusy(false); if (r.ok && body.itinerary) { setDraft(fromItinerary(body.itinerary)); setMessage('Itinerary finalized'); onSaved(); } else setMessage('Could not finalize itinerary'); }
  async function share() { const itinerary = draft.status === 'FINAL' && saved ? saved : await save(); if (!itinerary) return; setBusy(true); const r = await fetch(`/api/travel/itineraries/${itinerary.id}/share`, { method: 'POST' }); const body = await r.json() as { url?: string; sent?: { ok: boolean; error?: string }; error?: string }; setBusy(false); if (!r.ok || !body.url) { setMessage(body.error ?? 'Could not create share link'); return; } if (body.sent?.ok) setMessage('Itinerary shared in the traveller’s WhatsApp conversation'); else { await navigator.clipboard?.writeText(body.url); window.open(`https://wa.me/?text=${encodeURIComponent(`Your Oliday itinerary\n${body.url}`)}`, '_blank', 'noopener,noreferrer'); setMessage(body.sent?.error ? `Share link created. WhatsApp send failed: ${body.sent.error}` : 'Share link created and copied'); } onSaved(); }

  return <div className="space-y-5">
    <div className="flex flex-wrap items-center gap-2"><Button onClick={() => setDraft(freshDraft(lead))} variant="outline">New itinerary</Button>{itineraries.map((itinerary) => <Button key={itinerary.id} size="sm" variant={draft.itinerary_id === itinerary.id ? 'default' : 'ghost'} onClick={() => setDraft(fromItinerary(itinerary))}>V{itinerary.version} · {itinerary.status}</Button>)}</div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <div className="space-y-4">
        <Card><CardHeader><CardTitle>Itinerary details</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><Field label="Title"><Input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} placeholder="Magical Ladakh escape" /></Field><Field label="Hero image URL"><Input value={draft.hero_image_url} onChange={(e) => setDraft({ ...draft, hero_image_url: e.target.value })} placeholder="https://…" /></Field><Field label="Welcome summary" wide><Textarea value={draft.summary} onChange={(e) => setDraft({ ...draft, summary: e.target.value })} placeholder="A warm overview of the journey" /></Field></CardContent></Card>
        {draft.days.map((day, index) => <Card key={`${day.day_number}-${index}`}><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle>Day {index + 1}</CardTitle><div className="flex gap-1"><Button type="button" size="sm" variant="ghost" disabled={index === 0} onClick={() => move(index, -1)}>↑</Button><Button type="button" size="sm" variant="ghost" disabled={index === draft.days.length - 1} onClick={() => move(index, 1)}>↓</Button><Button type="button" size="sm" variant="ghost" disabled={draft.days.length === 1} onClick={() => setDraft({ ...draft, days: renumber(draft.days.filter((_, i) => i !== index)) })}>Remove</Button></div></div></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Field label="Date"><Input type="date" value={day.date} onChange={(e) => updateDay(index, { date: e.target.value })} /></Field><Field label="Day title"><Input value={day.title} onChange={(e) => updateDay(index, { title: e.target.value })} /></Field><Field label="Description" wide><Textarea className="min-h-28" value={day.description} onChange={(e) => updateDay(index, { description: e.target.value })} placeholder="Arrival, route, experience and pacing" /></Field><Field label="Hotel / stay"><Input value={day.hotel} onChange={(e) => updateDay(index, { hotel: e.target.value })} /></Field><Field label="Meals"><Input value={day.meals} onChange={(e) => updateDay(index, { meals: e.target.value })} /></Field><Field label="Transport"><Input value={day.transport} onChange={(e) => updateDay(index, { transport: e.target.value })} /></Field><Field label="Activities, one per line"><Textarea value={day.activities} onChange={(e) => updateDay(index, { activities: e.target.value })} /></Field></CardContent></Card>)}
        <Button variant="outline" onClick={() => setDraft((d) => ({ ...d, days: [...d.days, blankDay(d.days.length + 1, addDate(d.days.at(-1)?.date ?? ''))] }))}>Add day</Button>
        <Card><CardHeader><CardTitle>Traveller notes</CardTitle></CardHeader><CardContent className="grid gap-4"><Field label="Inclusions"><Textarea value={draft.inclusions} onChange={(e) => setDraft({ ...draft, inclusions: e.target.value })} placeholder="Hotels, transport, meals, activities…" /></Field><Field label="Exclusions"><Textarea value={draft.exclusions} onChange={(e) => setDraft({ ...draft, exclusions: e.target.value })} placeholder="Flights, personal expenses…" /></Field><Field label="Good to know"><Textarea value={draft.notes} onChange={(e) => setDraft({ ...draft, notes: e.target.value })} placeholder="Permits, weather, packing or pickup notes" /></Field></CardContent></Card>
      </div>
      <aside className="space-y-4 xl:sticky xl:top-5 xl:self-start"><Card className="overflow-hidden"><div className="bg-[#073f39] p-5 text-white"><Image src="/oliday_logo.png" alt="Oliday" width={150} height={48} className="h-auto w-32 brightness-0 invert" /><p className="mt-8 text-xs font-bold tracking-[0.2em] text-amber-200">PERSONALISED JOURNEY</p><h3 className="mt-2 text-2xl font-black">{draft.title || 'Your itinerary'}</h3><p className="mt-3 text-sm text-emerald-100">{draft.summary || `${lead.destination_primary ?? 'A memorable'} holiday, thoughtfully planned.`}</p></div><CardContent className="space-y-3 pt-5"><div className="flex items-end justify-between"><div><p className="text-xs font-bold text-[#0d8b76]">{lead.destination_primary}</p><p className="text-sm">{draft.days.length} days · {lead.adults} adults{lead.children ? ` + ${lead.children} children` : ''}</p></div><Image src="/oli.png" alt="Oli" width={72} height={92} className="h-20 w-auto" /></div>{draft.days.slice(0, 5).map((day) => <div key={day.day_number} className="border-l-2 border-[#0d8b76] pl-3"><p className="text-xs font-bold text-[#0d8b76]">DAY {day.day_number}</p><p className="text-sm font-semibold">{day.title || 'Add a title'}</p></div>)}{draft.days.length > 5 ? <p className="text-xs text-muted-foreground">+ {draft.days.length - 5} more days</p> : null}</CardContent></Card><div className="grid gap-2"><Button disabled={busy || draft.status === 'FINAL'} onClick={() => void save()}>{busy ? 'Saving…' : 'Save draft'}</Button><Button disabled={busy || draft.status === 'FINAL'} variant="secondary" onClick={() => void finalize()}>Finalize</Button>{saved ? <a className="inline-flex h-8 items-center justify-center rounded-lg border px-3 text-sm font-medium" href={`/api/travel/itineraries/${saved.id}/download`}>Download PDF</a> : null}<Button disabled={busy || !lead.conversation_id} className="bg-[#25D366] text-white hover:bg-[#20bd5a]" onClick={() => void share()}>Share on WhatsApp</Button>{message ? <p className="rounded-lg bg-muted p-3 text-sm">{message}</p> : null}</div></aside>
    </div>
  </div>;
}

function Field({ label, wide, children }: { label: string; wide?: boolean; children: ReactNode }) { return <div className={wide ? 'space-y-1.5 md:col-span-2' : 'space-y-1.5'}><Label>{label}</Label>{children}</div>; }
function blankDay(day_number: number, date = ''): DayDraft { return { day_number, date, title: '', description: '', hotel: '', meals: '', transport: '', activities: '' }; }
function addDate(value: string): string { if (!value) return ''; const d = new Date(`${value}T00:00:00Z`); d.setUTCDate(d.getUTCDate() + 1); return d.toISOString().slice(0, 10); }
function freshDraft(lead: TravelLead): Draft { const count = Math.max(1, lead.days ?? (lead.nights != null ? lead.nights + 1 : 1)); const days = Array.from({ length: count }, (_, i) => blankDay(i + 1, lead.travel_start_date ? addDays(lead.travel_start_date, i) : '')); days[0].title = `Arrival in ${lead.destination_primary ?? 'destination'}`; if (days.length > 1) days[days.length - 1].title = 'Departure'; return { itinerary_id: null, status: 'DRAFT', title: `${lead.destination_primary ?? 'Holiday'} itinerary`, summary: `A thoughtfully planned ${lead.days ?? count}-day journey for ${lead.traveller_name ?? 'our traveller'}.`, hero_image_url: '', inclusions: '', exclusions: '', notes: lead.special_requests ?? '', days }; }
function addDays(value: string, count: number): string { const d = new Date(`${value}T00:00:00Z`); d.setUTCDate(d.getUTCDate() + count); return d.toISOString().slice(0, 10); }
function fromItinerary(itinerary: Itinerary): Draft { const extras = itinerary.extras ?? {}; return { itinerary_id: itinerary.id, status: itinerary.status, title: itinerary.title, summary: itinerary.summary ?? '', hero_image_url: itinerary.hero_image_url ?? '', inclusions: typeof extras.inclusions === 'string' ? extras.inclusions : '', exclusions: typeof extras.exclusions === 'string' ? extras.exclusions : '', notes: typeof extras.notes === 'string' ? extras.notes : '', days: (itinerary.days ?? []).map((day) => ({ day_number: day.day_number, date: day.date ?? '', title: day.title, description: day.description ?? '', hotel: day.hotel ?? '', meals: day.meals ?? '', transport: day.transport ?? '', activities: (day.activities ?? []).join('\n') })) }; }
