'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { StatusBadge } from './status-badge';
import { ItineraryBuilder } from './itinerary-builder';
import type { LeadDetail } from '@/lib/travel/lead-detail';
import { budgetLabel, datesLabel, durationLabel, fmtDateTime, paxLabel, stayLabel } from '@/lib/travel/format';
import { formatMoney } from '@/lib/travel/money';
import { TRAVEL_LEAD_STATUSES } from '@/types/travel';

const tabs = ['Overview', 'WhatsApp', 'Trip requirement', 'Supplier quotes', 'Traveller quotes', 'Itinerary', 'Calls & notes', 'Tasks', 'Financials', 'Timeline'] as const;
type Tab = typeof tabs[number];

export function LeadDetailPage({ leadId, initialTab = 'Overview' }: { leadId: string; initialTab?: Tab }) {
  const [detail, setDetail] = useState<LeadDetail | null>(null);
  const [tab, setTab] = useState<Tab>(initialTab);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const load = useCallback(() => fetch(`/api/travel/leads/${leadId}`).then(async (r) => { const v = await r.json() as LeadDetail & { error?: string }; if (!r.ok) throw new Error(v.error ?? 'Could not load lead'); setDetail(v); }).catch((e: Error) => setError(e.message)), [leadId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    const db = createClient();
    const channel = db.channel(`travel-lead-${leadId}`)
      .on('postgres_changes', { event: '*', schema: 'public', table: 'supplier_quotes', filter: `travel_lead_id=eq.${leadId}` }, () => void load())
      .on('postgres_changes', { event: '*', schema: 'public', table: 'travel_lead_events', filter: `travel_lead_id=eq.${leadId}` }, () => void load())
      .on('postgres_changes', { event: '*', schema: 'public', table: 'callback_requests', filter: `travel_lead_id=eq.${leadId}` }, () => void load())
      .subscribe();
    return () => { void db.removeChannel(channel); };
  }, [leadId, load]);
  async function patchLead(patch: Record<string, unknown>) { setBusy(true); const r = await fetch(`/api/travel/leads/${leadId}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(patch) }); setBusy(false); if (!r.ok) setError('Could not update lead'); else await load(); }
  async function createRfq() { setBusy(true); const r = await fetch(`/api/travel/leads/${leadId}/rfqs`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ send: true }) }); setBusy(false); if (!r.ok) setError('Could not create RFQ'); else await load(); }
  async function addNote(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setBusy(true); const r = await fetch(`/api/travel/leads/${leadId}/interactions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ interaction_type: data.get('type'), summary: data.get('summary'), details: data.get('details'), next_follow_up_at: data.get('followup') || null }) }); setBusy(false); if (r.ok) { form.reset(); await load(); } else setError('Could not save note'); }
  async function makeTravellerQuote(supplierQuoteId: string) { setBusy(true); const r = await fetch(`/api/travel/leads/${leadId}/traveller-quotes`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ supplier_quote_id: supplierQuoteId }) }); setBusy(false); if (r.ok) { setTab('Traveller quotes'); await load(); } else setError('Could not create traveller quote'); }
  const lowest = useMemo<string | null>(() => detail ? detail.supplier_quotes.filter((q) => ['SUBMITTED', 'SHORTLISTED', 'SELECTED'].includes(q.status)).reduce<string | null>((best, q) => best === null || Number(q.total_supplier_cost) < Number(best) ? q.total_supplier_cost : best, null) : null, [detail]);
  if (error && !detail) return <Card><CardContent className="py-12 text-center text-destructive">{error}</CardContent></Card>;
  if (!detail) return <div className="py-24 text-center text-muted-foreground">Loading lead story…</div>;
  const { lead } = detail;
  return <div className="space-y-5">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold">{lead.traveller_name ?? detail.contact?.name ?? 'Traveller'}</h1><StatusBadge value={lead.status} /></div><p className="mt-1 text-muted-foreground">{[lead.destination_primary, durationLabel(lead), datesLabel(lead)].filter(Boolean).join(' • ')}</p><p className="mt-1 text-sm text-muted-foreground">{paxLabel(lead)} • {stayLabel(lead)}{lead.vehicle_type ? ` • ${lead.vehicle_type}` : ''}{lead.budget_amount ? ` • Budget ${budgetLabel(lead)}` : ''}</p></div><div className="flex flex-wrap gap-2"><select aria-label="Lead status" value={lead.status} disabled={busy} onChange={(e) => void patchLead({ status: e.target.value })} className="h-8 rounded-lg border bg-background px-2 text-sm">{TRAVEL_LEAD_STATUSES.map((s) => <option key={s}>{s}</option>)}</select><select aria-label="Assigned agent" value={lead.assigned_agent_id ?? ''} disabled={busy} onChange={(e) => void patchLead({ assigned_agent_id: e.target.value || null })} className="h-8 rounded-lg border bg-background px-2 text-sm"><option value="">Unassigned</option>{detail.members.map((m) => <option key={m.user_id} value={m.user_id}>{m.full_name}</option>)}</select><Button disabled={busy} onClick={() => void createRfq()}>Create & send RFQ</Button></div></div>
    {error ? <p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p> : null}
    <div className="flex gap-1 overflow-x-auto border-b pb-2">{tabs.map((name) => <Button key={name} size="sm" variant={tab === name ? 'default' : 'ghost'} onClick={() => setTab(name)}>{name}</Button>)}</div>
    {tab === 'Overview' ? <div className="grid gap-4 lg:grid-cols-3"><Card><CardHeader><CardTitle>Traveller</CardTitle></CardHeader><CardContent className="space-y-2"><p>{detail.contact?.phone ?? 'Phone unavailable'}</p><p>{lead.departure_city ? `From ${lead.departure_city}` : 'Departure city TBC'}</p>{lead.conversation_id ? <Link className="text-primary hover:underline" href={`/inbox?c=${lead.conversation_id}`}>Open WhatsApp conversation</Link> : <p className="text-muted-foreground">No linked conversation</p>}</CardContent></Card><Card><CardHeader><CardTitle>Supplier quotes</CardTitle></CardHeader><CardContent className="space-y-2">{detail.supplier_quotes.slice(0, 4).map((q) => <div key={q.id} className="flex justify-between"><span>{q.supplier?.name ?? 'Supplier'} · V{q.version}</span><span className="font-semibold">{formatMoney(q.total_supplier_cost, q.currency)}</span></div>)}{!detail.supplier_quotes.length ? <p className="text-muted-foreground">Waiting for supplier responses</p> : null}<button className="text-sm text-primary" onClick={() => setTab('Supplier quotes')}>Compare quotes →</button></CardContent></Card><Card><CardHeader><CardTitle>Sales</CardTitle></CardHeader><CardContent className="space-y-2">{detail.pricing_preview ? <><div className="flex justify-between"><span>Supplier cost</span><span>{formatMoney(detail.pricing_preview.supplier_cost)}</span></div><div className="flex justify-between"><span>Traveller total</span><span>{formatMoney(detail.pricing_preview.traveller_total)}</span></div><div className="flex justify-between font-semibold"><span>Gross profit</span><span>{formatMoney(detail.pricing_preview.gross_profit)}</span></div><div className="flex justify-between"><span>Margin</span><span>{detail.pricing_preview.margin_pct}%</span></div></> : <p className="text-muted-foreground">Pricing appears when supplier quotes arrive.</p>}</CardContent></Card>{lead.next_action_text ? <Card className="border-primary/30 lg:col-span-3"><CardContent><p className="text-xs font-semibold uppercase tracking-wide text-primary">Next action</p><p className="mt-1 text-lg font-semibold">{lead.next_action_text}</p>{lead.next_action_at ? <p className="text-sm text-muted-foreground">{fmtDateTime(lead.next_action_at)}</p> : null}</CardContent></Card> : null}</div> : null}
    {tab === 'WhatsApp' ? <Card><CardHeader><CardTitle>Recent WhatsApp history</CardTitle></CardHeader><CardContent className="space-y-2">{detail.recent_messages.map((m) => <div key={m.id} className={`max-w-2xl rounded-lg p-3 text-sm ${m.sender_type !== 'customer' ? 'ml-auto bg-primary/10' : 'bg-muted'}`}><p>{m.content_text ?? `[${m.content_type}]`}</p><p className="mt-1 text-[11px] text-muted-foreground">{fmtDateTime(m.created_at)}</p></div>)}{lead.conversation_id ? <Link className="inline-block text-primary hover:underline" href={`/inbox?c=${lead.conversation_id}`}>Continue in Inbox →</Link> : null}</CardContent></Card> : null}
    {tab === 'Trip requirement' ? <div className="grid gap-3"><RequirementRevisionForm lead={lead} leadId={leadId} busy={busy} setBusy={setBusy} reload={load} />{detail.requirement_versions.map((r) => <Card key={r.id}><CardHeader><CardTitle>Requirement V{r.version}</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Info label="Destination" value={[r.destination_primary, ...r.destinations].filter(Boolean).join(', ')} /><Info label="Dates" value={datesLabel(r)} /><Info label="Travellers" value={paxLabel(r)} /><Info label="Stay" value={stayLabel(r)} /><Info label="Rooms" value={r.room_configuration ?? String(r.room_count ?? 'TBC')} /><Info label="Transport" value={[r.vehicle_type, r.pickup_location, r.drop_location].filter(Boolean).join(' • ')} /><Info label="Budget" value={budgetLabel(r)} /><Info label="Change reason" value={r.change_reason ?? (r.version === 1 ? 'Original bot qualification' : '—')} /></CardContent></Card>)}</div> : null}
    {tab === 'Supplier quotes' ? <QuoteComparison detail={detail} lowest={lowest} busy={busy} onChoose={(id) => void makeTravellerQuote(id)} /> : null}
    {tab === 'Traveller quotes' ? <div className="grid gap-3 md:grid-cols-2">{detail.traveller_quotes.map((q) => <Card key={q.id}><CardHeader><div className="flex justify-between"><CardTitle>Traveller quote V{q.version}</CardTitle><StatusBadge value={q.status} /></div></CardHeader><CardContent className="space-y-2"><Info label="Supplier cost" value={formatMoney(q.supplier_cost, q.currency)} /><Info label="Selling price before tax" value={formatMoney(q.selling_price_before_tax, q.currency)} /><Info label={`GST (${q.gst_rate}%)`} value={formatMoney(q.gst_amount, q.currency)} /><Info label="Traveller total" value={formatMoney(q.traveller_total, q.currency)} /><Info label="Gross profit" value={`${formatMoney(q.gross_profit, q.currency)} · ${q.margin_pct}%`} />{q.status === 'DRAFT' ? <Button disabled={busy} onClick={() => void fetch(`/api/travel/traveller-quotes/${q.id}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'send' }) }).then(load)}>Send to traveller</Button> : null}</CardContent></Card>)}{!detail.traveller_quotes.length ? <p className="text-muted-foreground">Choose a supplier quote to build the traveller price.</p> : null}</div> : null}
    {tab === 'Itinerary' ? <ItineraryBuilder lead={lead} itineraries={detail.itineraries} onSaved={load} /> : null}
    {tab === 'Calls & notes' ? <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Record interaction</CardTitle></CardHeader><CardContent><form onSubmit={addNote} className="space-y-3"><select name="type" className="h-8 w-full rounded-lg border bg-background px-2"><option>CALL</option><option>NOTE</option><option>FOLLOW_UP</option><option>MEETING</option></select><Input name="summary" required placeholder="Customer wants a better Munnar resort" /><Textarea name="details" placeholder="Negotiation details and context" /><Input name="followup" type="datetime-local" /><Button disabled={busy}>Save interaction</Button></form></CardContent></Card><div className="space-y-3">{detail.interactions.map((i) => <Card key={i.id}><CardContent><div className="flex justify-between"><strong>{i.interaction_type}: {i.summary}</strong><span className="text-xs text-muted-foreground">{fmtDateTime(i.occurred_at)}</span></div>{i.details ? <p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{i.details}</p> : null}</CardContent></Card>)}</div></div> : null}
    {tab === 'Tasks' ? <div className="grid gap-3">{detail.tasks.map((t) => <Card key={t.id}><CardContent className="flex items-center justify-between"><div><p className="font-semibold">{t.title}</p><p className="text-sm text-muted-foreground">{t.due_at ? fmtDateTime(t.due_at) : 'No due date'}</p></div><StatusBadge value={t.status} /></CardContent></Card>)}</div> : null}
    {tab === 'Financials' ? <div className="grid gap-3 md:grid-cols-2">{detail.bookings.map((b) => <Link href={`/bookings/${b.id}`} key={b.id}><Card><CardHeader><CardTitle>{b.booking_number}</CardTitle></CardHeader><CardContent className="space-y-2"><Info label="Traveller total" value={formatMoney(b.traveller_total)} /><Info label="Customer balance" value={formatMoney(b.customer_balance)} /><Info label="Supplier balance" value={formatMoney(b.supplier_balance)} /><Info label="Gross profit" value={`${formatMoney(b.gross_profit)} · ${b.margin_pct}%`} /></CardContent></Card></Link>)}{!detail.bookings.length ? <p className="text-muted-foreground">Financial snapshots appear after quote acceptance.</p> : null}</div> : null}
    {tab === 'Timeline' ? <Timeline leadId={leadId} /> : null}
  </div>;
}

function Info({ label, value }: { label: string; value: string | null | undefined }) { return <div className="flex justify-between gap-4 border-b border-border/50 py-1"><span className="text-muted-foreground">{label}</span><span className="text-right font-medium">{value || '—'}</span></div>; }

function RequirementRevisionForm({ lead, leadId, busy, setBusy, reload }: { lead: LeadDetail['lead']; leadId: string; busy: boolean; setBusy: (v: boolean) => void; reload: () => void }) {
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const raw = Object.fromEntries(new FormData(form).entries()); setBusy(true); const r = await fetch(`/api/travel/leads/${leadId}/requirements`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ destination_primary: raw.destination_primary, travel_start_date: raw.travel_start_date || null, travel_end_date: raw.travel_end_date || null, budget_amount: raw.budget_amount || null, special_requests: raw.special_requests, reason: raw.reason, create_rfq: raw.create_rfq === 'on', send: true }) }); setBusy(false); if (r.ok) reload(); }
  return <Card><CardHeader><CardTitle>Revise requirement</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 md:grid-cols-6"><Input name="destination_primary" aria-label="Destination" defaultValue={lead.destination_primary ?? ''} placeholder="Destination" /><Input name="travel_start_date" aria-label="Start date" type="date" defaultValue={lead.travel_start_date ?? ''} /><Input name="travel_end_date" aria-label="End date" type="date" defaultValue={lead.travel_end_date ?? ''} /><Input name="budget_amount" aria-label="Budget" type="number" defaultValue={lead.budget_amount ?? ''} placeholder="Budget" /><Input name="reason" aria-label="Revision reason" required placeholder="Reason for revision" /><div className="flex items-center gap-2"><label className="text-xs"><input type="checkbox" name="create_rfq" defaultChecked /> Send RFQ V{lead.current_requirement_version + 1}</label><Button disabled={busy}>Save</Button></div><Textarea className="md:col-span-6" name="special_requests" defaultValue={lead.special_requests ?? ''} placeholder="Updated special requests" /></form></CardContent></Card>;
}

function QuoteComparison({ detail, lowest, busy, onChoose }: { detail: LeadDetail; lowest: string | null; busy: boolean; onChoose: (id: string) => void }) {
  const quotes = detail.supplier_quotes.filter((q) => ['SUBMITTED', 'SHORTLISTED', 'SELECTED'].includes(q.status));
  if (!quotes.length) return <Card><CardContent className="py-12 text-center text-muted-foreground">No supplier quotes have arrived yet.</CardContent></Card>;
  return <div className="grid gap-3 lg:grid-cols-3">{quotes.map((q) => <Card key={q.id} className={q.total_supplier_cost === lowest ? 'ring-2 ring-emerald-500' : ''}><CardHeader><div className="flex items-start justify-between"><div><CardTitle>{q.supplier?.name ?? 'Supplier'}</CardTitle><p className="mt-1 text-xs text-muted-foreground">Quote V{q.version}{q.supplier?.rating ? ` · ★ ${q.supplier.rating}` : ''}</p></div>{q.total_supplier_cost === lowest ? <span className="text-xs font-semibold text-emerald-600">Lowest cost</span> : null}</div></CardHeader><CardContent className="space-y-2"><Info label="Hotel" value={formatMoney(q.hotel_cost)} /><Info label="Transport" value={formatMoney(q.transport_cost)} /><Info label="Activities" value={formatMoney(q.activities_cost)} /><Info label="Other" value={formatMoney(q.other_cost)} /><div className="flex justify-between border-t pt-2 text-lg font-bold"><span>Total cost</span><span>{formatMoney(q.total_supplier_cost)}</span></div>{q.hotel_details.length ? <p className="text-sm"><span className="text-muted-foreground">Hotels: </span>{q.hotel_details.map((h) => `${h.name}${h.room_category ? ` (${h.room_category})` : ''}`).join(', ')}</p> : null}{q.inclusions ? <p className="text-sm"><span className="text-muted-foreground">Includes: </span>{q.inclusions}</p> : null}{q.exclusions ? <p className="text-sm"><span className="text-muted-foreground">Excludes: </span>{q.exclusions}</p> : null}<Button className="w-full" disabled={busy} onClick={() => onChoose(q.id)}>Use as traveller quote</Button></CardContent></Card>)}</div>;
}

function Timeline({ leadId }: { leadId: string }) {
  const [items, setItems] = useState<{ id: string; at: string; title: string; body?: string | null }[]>([]);
  useEffect(() => { void fetch(`/api/travel/leads/${leadId}/timeline`).then((r) => r.json()).then((v: { timeline?: typeof items; entries?: typeof items }) => setItems(v.timeline ?? v.entries ?? [])); }, [leadId]);
  return <Card><CardContent className="space-y-0">{items.length ? items.map((item) => <div key={item.id} className="relative border-l-2 border-primary/25 py-3 pl-5 before:absolute before:-left-[5px] before:top-5 before:h-2 before:w-2 before:rounded-full before:bg-primary"><p className="font-medium">{item.title}</p>{item.body ? <p className="text-sm text-muted-foreground">{item.body}</p> : null}<p className="text-xs text-muted-foreground">{fmtDateTime(item.at)}</p></div>) : <p className="py-6 text-sm text-muted-foreground">No timeline activity yet.</p>}</CardContent></Card>;
}
