'use client';

import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { formatMoney } from '@/lib/travel/money';

interface QuoteView { traveller_first_name: string | null; destination: string | null; destinations: string[]; nights: number | null; days: number | null; travel_month: string | null; adults: number; children: number; hotel_category: string | null; vehicle_type: string | null; quote: { version: number; title: string | null; currency: string; price_before_tax: string; gst_rate: string; gst_amount: string; total: string; valid_until: string | null; inclusions: string | null; exclusions: string | null; cancellation_policy: string | null; notes: string | null; status: string }; itinerary: { title: string; summary: string | null; hero_image_url: string | null; days: { day_number: number; title: string; description: string | null; hotel: string | null; meals: string | null; transport: string | null; activities: string[] }[] } | null }
export function PublicTravellerQuote({ token }: { token: string }) {
  const endpoint = `/api/public/travel/quote/${encodeURIComponent(token)}`; const [view, setView] = useState<QuoteView | null>(null); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<string | null>(null); const [note, setNote] = useState('');
  useEffect(() => { void fetch(endpoint).then(async (r) => { const b = await r.json() as QuoteView & { error?: string }; if (!r.ok) throw new Error(b.error ?? 'This quote is unavailable'); setView(b); }).catch((e: Error) => setError(e.message)); }, [endpoint]);
  async function action(value: 'accept' | 'request_change' | 'talk_to_expert') { const r = await fetch(endpoint, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: value, note }) }); const b = await r.json() as { status?: string; booking_number?: string | null; error?: string }; if (!r.ok) setError(b.error ?? 'Could not update quote'); else setResult(b.booking_number ? `Package accepted. Booking ${b.booking_number} is confirmed.` : value === 'accept' ? 'Package accepted.' : 'Your travel expert has been notified.'); }
  if (!view) return <main className="min-h-screen bg-muted/30 p-8 text-center">{error ?? 'Opening your Oliday package…'}</main>;
  return <main className="min-h-screen bg-muted/30"><div className="mx-auto max-w-4xl space-y-5 px-4 py-10"><div><p className="text-sm font-medium text-primary">Your Oliday package · Quote V{view.quote.version}</p><h1 className="text-3xl font-bold">{view.quote.title ?? `${view.destination ?? 'Your'} holiday`}</h1><p className="mt-1 text-muted-foreground">{view.travel_month ?? 'Flexible dates'} · {view.nights ?? '—'}N/{view.days ?? '—'}D · {view.adults} adults{view.children ? ` + ${view.children} children` : ''}</p></div><Card><CardHeader><CardTitle>Package price</CardTitle></CardHeader><CardContent className="space-y-2"><Price label="Price before tax" value={formatMoney(view.quote.price_before_tax, view.quote.currency)} /><Price label={`GST (${view.quote.gst_rate}%)`} value={formatMoney(view.quote.gst_amount, view.quote.currency)} /><div className="flex justify-between border-t pt-3 text-2xl font-bold"><span>Traveller total</span><span>{formatMoney(view.quote.total, view.quote.currency)}</span></div>{view.quote.valid_until ? <p className="text-xs text-muted-foreground">Valid until {new Date(view.quote.valid_until).toLocaleDateString('en-IN')}</p> : null}</CardContent></Card>{view.itinerary ? <Card><CardHeader><CardTitle>{view.itinerary.title}</CardTitle></CardHeader><CardContent className="space-y-3">{view.itinerary.days.map((day) => <div key={day.day_number} className="border-l-2 border-primary/30 pl-4"><p className="font-semibold">Day {day.day_number}: {day.title}</p><p className="text-sm text-muted-foreground">{day.description}</p>{day.hotel ? <p className="text-sm">Stay: {day.hotel}</p> : null}</div>)}</CardContent></Card> : null}<div className="grid gap-3 md:grid-cols-2"><Card><CardHeader><CardTitle>Inclusions</CardTitle></CardHeader><CardContent className="whitespace-pre-wrap text-sm">{view.quote.inclusions ?? 'As discussed with your travel expert.'}</CardContent></Card><Card><CardHeader><CardTitle>Exclusions & cancellation</CardTitle></CardHeader><CardContent className="space-y-3 whitespace-pre-wrap text-sm"><p>{view.quote.exclusions ?? 'Please ask your expert for exclusions.'}</p><p>{view.quote.cancellation_policy}</p></CardContent></Card></div>{result ? <Card className="border-emerald-500"><CardContent className="py-6 text-center font-semibold text-emerald-700">{result}</CardContent></Card> : <Card><CardContent className="space-y-3"><Textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Tell us what you would like changed" /><div className="grid gap-2 sm:grid-cols-3"><Button onClick={() => void action('accept')}>Accept package</Button><Button variant="outline" onClick={() => void action('request_change')}>Request change</Button><Button variant="secondary" onClick={() => void action('talk_to_expert')}>Talk to expert</Button></div>{error ? <p className="text-sm text-destructive">{error}</p> : null}</CardContent></Card>}</div></main>;
}
function Price({ label, value }: { label: string; value: string }) { return <div className="flex justify-between"><span className="text-muted-foreground">{label}</span><span className="font-medium">{value}</span></div>; }
