'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

interface SupplierView { supplier_name: string; rfq_version: number; deadline: string | null; requirement: Record<string, unknown>; existing_quote: Record<string, unknown> | null }

export function PublicSupplierQuote({ token }: { token: string }) {
  const endpoint = `/api/public/travel/supplier-quote/${encodeURIComponent(token)}`;
  const [view, setView] = useState<SupplierView | null>(null); const [error, setError] = useState<string | null>(null); const [done, setDone] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { void fetch(endpoint).then(async (r) => { const b = await r.json() as SupplierView & { error?: string }; if (!r.ok) throw new Error(b.error ?? 'This quote link is unavailable'); setView(b); }).catch((e: Error) => setError(e.message)); }, [endpoint]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setBusy(true); setError(null); const body = Object.fromEntries(data.entries()); const r = await fetch(endpoint, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...body, hotel_details: body.hotel_name ? [{ name: body.hotel_name, room_category: body.room_category }] : [], transport_details: { vehicle: body.vehicle, notes: body.transport_notes }, items: [] }) }); const result = await r.json() as { error?: string }; setBusy(false); if (!r.ok) setError(result.error ?? 'Could not submit quote'); else setDone(true); }
  if (error && !view) return <PublicShell><Card><CardContent className="py-12 text-center text-destructive">{error}</CardContent></Card></PublicShell>;
  if (!view) return <PublicShell><p className="text-center text-muted-foreground">Checking secure quote link…</p></PublicShell>;
  if (done) return <PublicShell><Card><CardContent className="py-12 text-center"><h1 className="text-2xl font-bold">Quote received</h1><p className="mt-2 text-muted-foreground">Thank you. Oliday can now compare your option with the other responses.</p></CardContent></Card></PublicShell>;
  const r = view.requirement;
  return <PublicShell><div className="space-y-5"><div><p className="text-sm font-medium text-primary">Oliday supplier portal</p><h1 className="text-2xl font-bold">Hello {view.supplier_name}, please quote this trip</h1><p className="text-muted-foreground">RFQ V{view.rfq_version}{view.deadline ? ` · Required by ${new Date(view.deadline).toLocaleString('en-IN')}` : ''}</p></div><Card><CardHeader><CardTitle>Trip requirement</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2"><Line label="Destination" value={[r.destination, ...((r.destinations as string[] | undefined) ?? [])].filter(Boolean).join(', ')} /><Line label="Dates" value={String(r.travel_month ?? r.travel_start_date ?? 'Flexible / TBC')} /><Line label="Duration" value={`${r.nights ?? '—'} nights / ${r.days ?? '—'} days`} /><Line label="Travellers" value={`${r.adults ?? 0} adults + ${r.children ?? 0} children + ${r.infants ?? 0} infants`} /><Line label="Rooms" value={`${r.room_count ?? '—'} · ${r.room_configuration ?? ''}`} /><Line label="Stay" value={`${r.hotel_category ?? '—'} · ${r.meal_plan ?? ''}`} /><Line label="Transport" value={`${r.vehicle_type ?? '—'} · ${r.pickup_location ?? ''} to ${r.drop_location ?? ''}`} /><Line label="Special requests" value={String(r.special_requests ?? 'None')} /></CardContent></Card><Card><CardHeader><CardTitle>{view.existing_quote ? 'Submit a revised B2B quote' : 'Your B2B quote'}</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['hotel_cost','Hotel cost'],['transport_cost','Transport cost'],['activities_cost','Activities'],['other_cost','Other'],['supplier_tax_amount','Supplier tax']].map(([name,label]) => <div className="space-y-1" key={name}><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type="number" min="0" step="0.01" defaultValue={String(view.existing_quote?.[name] ?? '0')} /></div>)}</div><div className="grid gap-3 sm:grid-cols-2"><Field name="hotel_name" label="Hotel name(s)" /><Field name="room_category" label="Room category" /><Field name="vehicle" label="Vehicle" /><Field name="valid_until" label="Quote valid until" type="date" /></div><Area name="inclusions" label="Inclusions" /><Area name="exclusions" label="Exclusions" /><Area name="cancellation_policy" label="Cancellation policy" /><Area name="supplier_notes" label="Notes for Oliday" />{error ? <p className="text-sm text-destructive">{error}</p> : null}<Button disabled={busy} size="lg">{busy ? 'Submitting…' : view.existing_quote ? 'Submit revised quote' : 'Submit quote'}</Button></form></CardContent></Card></div></PublicShell>;
}

function PublicShell({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-muted/30 px-4 py-10"><div className="mx-auto max-w-4xl">{children}</div></main>; }
function Line({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 border-b py-2"><span className="text-muted-foreground">{label}</span><span className="text-right font-medium">{value || '—'}</span></div>; }
function Field({ name, label, type = 'text' }: { name: string; label: string; type?: string }) { return <div className="space-y-1"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} /></div>; }
function Area({ name, label }: { name: string; label: string }) { return <div className="space-y-1"><Label htmlFor={name}>{label}</Label><Textarea id={name} name={name} /></div>; }
