'use client';

import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { formatMoney } from '@/lib/travel/money';

type Row = Record<string, unknown>;
interface Funnel { stages: { key: string; label: string; count: number; pct_of_first: string }[] }
export function ReportsPage() {
  const [reports, setReports] = useState<Record<string, Row[]>>({}); const [funnel, setFunnel] = useState<Funnel | null>(null);
  useEffect(() => { void Promise.all(['funnel','campaigns','destinations','agents','suppliers'].map(async (kind) => { const r = await fetch(`/api/travel/reports?kind=${kind}`); return [kind, await r.json()] as const; })).then((values) => { const next: Record<string, Row[]> = {}; for (const [kind, body] of values) { if (kind === 'funnel') setFunnel((body as { funnel?: Funnel }).funnel ?? null); else next[kind] = (body as { rows?: Row[] }).rows ?? []; } setReports(next); }); }, []);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Oliday reports</h1><p className="mt-1 text-sm text-muted-foreground">Lead conversion, revenue, profit, agent and supplier performance</p></div>{funnel ? <Card><CardHeader><CardTitle>Lead funnel</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{funnel.stages.map((s) => <div key={s.key} className="rounded-lg bg-muted p-3"><p className="text-xs text-muted-foreground">{s.label}</p><p className="text-2xl font-bold">{s.count}</p><p className="text-xs">{s.pct_of_first}% of enquiries</p></div>)}</CardContent></Card> : null}{(['campaigns','destinations','agents','suppliers'] as const).map((kind) => <Card key={kind}><CardHeader><CardTitle className="capitalize">{kind}</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-2">Name</th><th className="p-2">Leads / RFQs</th><th className="p-2">Bookings / Responses</th><th className="p-2">Conversion</th><th className="p-2">Revenue / value</th><th className="p-2">Gross profit</th></tr></thead><tbody>{(reports[kind] ?? []).map((row) => <tr className="border-b" key={String(row.key ?? row.supplier_id)}><td className="p-2 font-medium">{String(row.label ?? row.name)}</td><td className="p-2">{String(row.leads ?? row.rfqs ?? 0)}</td><td className="p-2">{String(row.bookings ?? row.responses ?? 0)}</td><td className="p-2">{String(row.conversion_pct ?? row.response_rate_pct ?? '0')}%</td><td className="p-2">{formatMoney(String(row.revenue ?? row.total_booking_value ?? '0'))}</td><td className="p-2">{formatMoney(String(row.gross_profit ?? '0'))}</td></tr>)}</tbody></table></div></CardContent></Card>)}</div>;
}
