'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import type { TravelSettings as Settings } from '@/types/travel';

export function TravelSettings() {
  const [settings, setSettings] = useState<Settings | null>(null); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void fetch('/api/travel/settings').then((r) => r.json()).then((b: { settings?: Settings }) => setSettings(b.settings ?? null)); }, []);
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget).entries()); const numbers = ['max_suppliers_per_rfq','min_quotes_before_notification','rfq_deadline_hours','supplier_reminder_hours','supplier_max_reminders','gst_rate','default_markup_value','margin_warning_pct','margin_approval_pct','traveller_quote_validity_days']; const body: Record<string, unknown> = { ...data }; for (const key of numbers) body[key] = data[key] === '' ? null : Number(data[key]); body.auto_send_rfq = data.auto_send_rfq === 'on'; body.auto_notify_traveller = data.auto_notify_traveller === 'on'; const r = await fetch('/api/travel/settings', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const result = await r.json() as { settings?: Settings; error?: string }; if (r.ok && result.settings) { setSettings(result.settings); setMessage('Oliday settings saved.'); } else setMessage(result.error ?? 'Could not save settings. Admin access is required.'); }
  if (!settings) return <Card><CardContent className="py-10 text-muted-foreground">Loading Oliday settings…</CardContent></Card>;
  return <Card><CardHeader><CardTitle>Oliday automation and pricing</CardTitle><p className="text-sm text-muted-foreground">Supplier matching, response thresholds, tax and margin rules used across every quote.</p></CardHeader><CardContent><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><NumberField name="max_suppliers_per_rfq" label="Suppliers per RFQ" value={settings.max_suppliers_per_rfq} /><NumberField name="min_quotes_before_notification" label="Quotes before traveller notification" value={settings.min_quotes_before_notification} /><NumberField name="rfq_deadline_hours" label="RFQ deadline (hours)" value={settings.rfq_deadline_hours} /><NumberField name="supplier_reminder_hours" label="Supplier reminder after (hours)" value={settings.supplier_reminder_hours} /><NumberField name="supplier_max_reminders" label="Maximum supplier reminders" value={settings.supplier_max_reminders} /><NumberField name="traveller_quote_validity_days" label="Traveller quote validity (days)" value={settings.traveller_quote_validity_days} /><NumberField name="gst_rate" label="Default GST rate (%)" value={settings.gst_rate} step="0.01" /><div className="space-y-1"><Label htmlFor="gst_taxable_base">GST taxable base</Label><select id="gst_taxable_base" name="gst_taxable_base" defaultValue={settings.gst_taxable_base} className="h-8 w-full rounded-lg border bg-background px-2"><option value="selling_price">Selling price</option><option value="markup">Markup only</option></select></div><NumberField name="default_markup_value" label="Default markup" value={settings.default_markup_value} step="0.01" /><div className="space-y-1"><Label htmlFor="default_markup_type">Markup type</Label><select id="default_markup_type" name="default_markup_type" defaultValue={settings.default_markup_type} className="h-8 w-full rounded-lg border bg-background px-2"><option value="percent">Percent</option><option value="fixed">Fixed amount</option></select></div><NumberField name="margin_warning_pct" label="Margin warning below (%)" value={settings.margin_warning_pct} step="0.01" /><NumberField name="margin_approval_pct" label="Require approval below (%)" value={settings.margin_approval_pct ?? ''} step="0.01" /><label className="flex items-center gap-2"><input type="checkbox" name="auto_send_rfq" defaultChecked={settings.auto_send_rfq} /> Automatically send new RFQs</label><label className="flex items-center gap-2"><input type="checkbox" name="auto_notify_traveller" defaultChecked={settings.auto_notify_traveller} /> Notify traveller when quotes are ready</label><div className="sm:col-span-2"><Button>Save settings</Button>{message ? <span className="ml-3 text-sm text-muted-foreground">{message}</span> : null}</div></form></CardContent></Card>;
}
function NumberField({ name, label, value, step = '1' }: { name: string; label: string; value: string | number; step?: string }) { return <div className="space-y-1"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type="number" min="0" step={step} defaultValue={value} /></div>; }
